on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: |
          echo "Current directory: $PWD"
          echo "inside the directory: $ls"

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          whoami
          echo "${{ secrets.GCP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa    
          ssh-keyscan 34.16.161.239 >> /home/runner/.ssh/known_hosts
          cat '/home/runner/.ssh/known_hosts'
          echo "end of ssh key setup"
           
      - name: Connect to EC2 and Run Commands
        run: |
          ssh -vvv -o StrictHostKeyChecking=no pavitrabolla123@34.16.161.239
           echo "connection made"

          
      - name: Connect to EC2 and Copy Files
        run: |
          ssh -vvv -o StrictHostKeyChecking=no pavitrabolla123@34.16.161.239 "cd /var/www/html/ && chmod 740 html && rm -rf * && git init && git clone https://github.com/bpavithra18/DevOps_GitActions.git && cd DevOps_GitActions"
